jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.image }}

    steps:
      - checkout: self
        submodules: true

      - task: CmdLine@2
        inputs:
          script: |
            gradle --version
            gradle wrapper
        displayName: "Gradle Wrapper"

      - task: Gradle@2
        inputs:
          jdkVersionOption: "1.11"
          tasks: "tasks"
        displayName: "Gradle Tasks"

      # cpp tasks
      - task: Gradle@2
        inputs:
          options: "-b cpp.gradle"
          jdkVersionOption: "1.11"
          tasks: "codegen"
        displayName: "C++ Codegen"

      - task: Gradle@2
        inputs:
          options: "-b cpp.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "assembleDebug assembleRelease"
        displayName: "C++ Build(Assemble)"

      - task: Gradle@2
        inputs:
          options: "-b cpp.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "build" # include 'test'
        displayName: "C++ Test"

      # java tasks
      - task: Gradle@2
        inputs:
          options: "-b build.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "assemble"
        displayName: "Java Build(Assemble)"

      - task: Gradle@2
        inputs:
          options: "-b build.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "test"
          publishJUnitResults: true
          testResultsFiles: "**/TEST-*.xml"
        displayName: "Java Test - JUnit5"
