/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_luncliff_Module */

#ifndef _Included_dev_luncliff_Module
#define _Included_dev_luncliff_Module
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_luncliff_Module
 * Method:    isTestMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dev_luncliff_Module_isTestMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
